// <auto-generated />
using System;
using GestionInventario.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionInventario.Migrations
{
    [DbContext(typeof(GestionInventariosContext))]
    partial class GestionInventariosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionInventario.Models.Ajuste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int?>("IdAlmacen")
                        .HasColumnType("int")
                        .HasColumnName("id_almacen");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<string>("Motivo")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("PK__Ajuste__3213E83F391B0EE8");

                    b.HasIndex("IdAlmacen");

                    b.HasIndex("IdProducto");

                    b.ToTable("Ajuste", (string)null);
                });

            modelBuilder.Entity("GestionInventario.Models.Almacen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PK__Almacen__3213E83F3BAEA390");

                    b.ToTable("Almacen", (string)null);
                });

            modelBuilder.Entity("GestionInventario.Models.Categorium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3213E83FE17FBEF7");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("GestionInventario.Models.Entradum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int?>("IdAlmacen")
                        .HasColumnType("int")
                        .HasColumnName("id_almacen");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.HasKey("Id")
                        .HasName("PK__Entrada__3213E83F3D86FD45");

                    b.HasIndex("IdAlmacen");

                    b.HasIndex("IdProducto");

                    b.ToTable("Entrada");
                });

            modelBuilder.Entity("GestionInventario.Models.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadActual")
                        .HasColumnType("int")
                        .HasColumnName("cantidad_actual");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int?>("IdAlmacen")
                        .HasColumnType("int")
                        .HasColumnName("id_almacen");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.HasKey("Id")
                        .HasName("PK__Inventar__3213E83F6FF81F6D");

                    b.HasIndex("IdAlmacen");

                    b.HasIndex("IdProducto");

                    b.ToTable("Inventario", (string)null);
                });

            modelBuilder.Entity("GestionInventario.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PK__Producto__3213E83F4BC45669");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdProveedor");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("GestionInventario.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contacto")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contacto");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PK__Proveedo__3213E83FA1CD6826");

                    b.ToTable("Proveedor", (string)null);
                });

            modelBuilder.Entity("GestionInventario.Models.Salidum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int?>("IdAlmacen")
                        .HasColumnType("int")
                        .HasColumnName("id_almacen");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.HasKey("Id")
                        .HasName("PK__Salida__3213E83FBC425886");

                    b.HasIndex("IdAlmacen");

                    b.HasIndex("IdProducto");

                    b.ToTable("Salida");
                });

            modelBuilder.Entity("GestionInventario.Models.Ajuste", b =>
                {
                    b.HasOne("GestionInventario.Models.Almacen", "IdAlmacenNavigation")
                        .WithMany("Ajustes")
                        .HasForeignKey("IdAlmacen")
                        .HasConstraintName("FK__Ajuste__id_almac__4E88ABD4");

                    b.HasOne("GestionInventario.Models.Producto", "IdProductoNavigation")
                        .WithMany("Ajustes")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__Ajuste__id_produ__4D94879B");

                    b.Navigation("IdAlmacenNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("GestionInventario.Models.Entradum", b =>
                {
                    b.HasOne("GestionInventario.Models.Almacen", "IdAlmacenNavigation")
                        .WithMany("Entrada")
                        .HasForeignKey("IdAlmacen")
                        .HasConstraintName("FK__Entrada__id_alma__46E78A0C");

                    b.HasOne("GestionInventario.Models.Producto", "IdProductoNavigation")
                        .WithMany("Entrada")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__Entrada__id_prod__45F365D3");

                    b.Navigation("IdAlmacenNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("GestionInventario.Models.Inventario", b =>
                {
                    b.HasOne("GestionInventario.Models.Almacen", "IdAlmacenNavigation")
                        .WithMany("Inventarios")
                        .HasForeignKey("IdAlmacen")
                        .HasConstraintName("FK__Inventari__id_al__52593CB8");

                    b.HasOne("GestionInventario.Models.Producto", "IdProductoNavigation")
                        .WithMany("Inventarios")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__Inventari__id_pr__5165187F");

                    b.Navigation("IdAlmacenNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("GestionInventario.Models.Producto", b =>
                {
                    b.HasOne("GestionInventario.Models.Categorium", "IdCategoriaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .HasConstraintName("FK__Producto__id_cat__412EB0B6");

                    b.HasOne("GestionInventario.Models.Proveedor", "IdProveedorNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdProveedor")
                        .HasConstraintName("FK__Producto__id_pro__403A8C7D");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdProveedorNavigation");
                });

            modelBuilder.Entity("GestionInventario.Models.Salidum", b =>
                {
                    b.HasOne("GestionInventario.Models.Almacen", "IdAlmacenNavigation")
                        .WithMany("Salida")
                        .HasForeignKey("IdAlmacen")
                        .HasConstraintName("FK__Salida__id_almac__4AB81AF0");

                    b.HasOne("GestionInventario.Models.Producto", "IdProductoNavigation")
                        .WithMany("Salida")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__Salida__id_produ__49C3F6B7");

                    b.Navigation("IdAlmacenNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("GestionInventario.Models.Almacen", b =>
                {
                    b.Navigation("Ajustes");

                    b.Navigation("Entrada");

                    b.Navigation("Inventarios");

                    b.Navigation("Salida");
                });

            modelBuilder.Entity("GestionInventario.Models.Categorium", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("GestionInventario.Models.Producto", b =>
                {
                    b.Navigation("Ajustes");

                    b.Navigation("Entrada");

                    b.Navigation("Inventarios");

                    b.Navigation("Salida");
                });

            modelBuilder.Entity("GestionInventario.Models.Proveedor", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
